env:
  browser: true
  es2021: true

extends:
  - google
  - plugin:react/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

settings:
  react:
    version: detect

rules:
  max-len: 
    - error
    - code: 120
    - ignoreUrls: true
    - ignoreComments: true
    - ignoreStrings: true
    - ignoreTemplateLiterals: true
  object-curly-spacing: 
    - error
    - always
  react/prop-types: warn
  no-trailing-spaces: error
  eol-last: 
    - error
    - always